#+title: General Thoughts on Summer - Personal 

Sitting in the library prepping for the last test before the break, just
taking some time to breathe. The first year at college has been a wild
transition. Met many people, learned many things, scored an internship,
progressed in terms of programming. Over the summer and into December, I
will be working a co-op in town for GE aviation, programming flight
systems and routing programs. Primarily I will be working with Visual
Basic, and though I would much prefer C#, I am excited for the chance to
work in a formal programming environment. They use Git to manage their
control versions locally, so I'm glad I took the advice of a career fair
recruiter and learned it over spring.

After today, I have two weeks of free space. I intend to do some
catching up with my friends on Guildwars, because classes. Just ordered
a highly recommended
[[http://www.newegg.com/Product/Product.aspx?Item=N82E16826249066][headset]]
50% off, can't wait to try it out. Finally won't have to use my laptop
next to my desktop as a Skype reliance.

Life is good.
