#+title: Weekend 

This past week has been crazy. Went in to work on Saturday and ended up
working from noon to 8, had a good time though. Got some decent overtime
in, and pizza and mountain dew was had by everyone who was at the
office. My manager has not been getting sleep, since we are in the
equivalent of finals week for our process. This has lead to him being
very loopy, but overall more fun to work with.

On Friday night, me and the new roommate(Sven) LAN'd it up over at
Ryan's house. Had the opportunity to see the leap motion in action, and
holy cow, was it ever worth it. There are many opportunities for this
device in the future, but since it has only come out in the past month
or so, it is still pretty rough. However, you do get the ability to fly
around in Google earth using your hands. Currently, no convenient method
exists for mapping motions to keys, though.

The leap motion has a path paved out for it though. It can recognize
motion and gestures and use them to store MIDI files, a sound type used
by many applications. It should be possible to use midi files to map
motions into a key. I look very forward to this in the future. Imagine,
Skyrim, where one hand is your sword and the other your shield?!
Beautiful.
