
#+title: org habit syntax reference
#+title_extra: 
#+filetags: 
#+pubdate: <2021-02-03>
#+post_type: note


A habit has the following properties:

- has TODO
- has SCHEDULED:

#+begin_example
\* TODO something
\SCHEDULED: <2020-10-27 Tue ++1w>
#+end_example

- ++1w meaning: increase one week after scheduled date (keep increasing by one week until in future), keep day
- .+1w meaning: increase one week after NOW, time when marked done

Text from the [[https://orgmode.org/manual/Tracking-your-habits.html][manual]]:

1. The habit is a TODO item, with a TODO keyword representing an open state.
2. The property ‘STYLE’ is set to the value ‘habit’ (see Properties and Columns).
3. The TODO has a scheduled date, usually with a ‘.+’ style repeat interval. A ‘++’ style may be appropriate for habits with time constraints, e.g., must be done on weekends, or a ‘+’ style for an unusual habit that can have a backlog, e.g., weekly reports.
4. The TODO may also have minimum and maximum ranges specified by using the syntax ‘.+2d/3d’, which says that you want to do the task at least every three days, but at most every two days.
5. State logging for the DONE state is enabled (see Tracking TODO state changes), in order for historical data to be represented in the consistency graph. If it is not enabled it is not an error, but the consistency graphs are largely meaningless.

NB: number *2* is what separates a HABIT from a repeating scheduled headline. I think there are some org-agenda implications for "consistency feedback" if you use that.