#+title: annoying org typing slowdowns
#+pubdate: <2020-11-01>

This is a list of things I had to turn off to not fuck with my typing speed in emacs org-mode buffers (sometimes I am really sensitive to latency/breaks in typing). For context, I usually run things in one really big notes file.

- smartparens mode
- modeline
- git-gutter mode
- timers that query the current buffer I'm typing in
- emojify-mode
- flyspell-mode (switched to a keybind to flyspell the buffer)
- (rarely) font-locking
  - related: font-locking takes longer if you have a really big emacs window (ie hidpi fullscreen emacs will lag, but if you float that bad boy in the center you will have a good time).
- (rarely) irc volume
- (rarely) having a large window (this makes the redisplay cost higher)

You can see how I'm doing this [[https://github.com/neeasade/emacs.d/blob/3f99869ec8ebabf5caf49a3c601092a4702c1342/lisp/trees/org.el#L425-L446][here]] and [[https://github.com/neeasade/emacs.d/blob/master/lisp/trees/editing.el#L11][here]].

These were all super annoying to track down because I would have to wait until I was caffienated enough to be "sensitive" to the speed and then profile everything. But now the feeling is SUPER COMFY.

Related: [[https://github.com/rnkn/olivetti][olivetti-mode]] has some nice display settings that don't takeover everything, for the pretty.

Related pain: https://emacshorrors.com/posts/self-insert-command.html
