#+title: The Calf Path
#+pubdate: <2020-12-17>

#+OPTIONS: \n:t

A poem by [[https://en.wikipedia.org/wiki/Sam_Walter_Foss][Sam Foss]].

** I.

One day through the primeval wood
A calf walked home as good calves should;

But made a trail all bent askew,
A crooked trail as all calves do.

Since then three hundred years have fled,
And I infer the calf is dead.

** II.

But still he left behind his trail,
And thereby hangs my moral tale.

The trail was taken up next day,
By a lone dog that passed that way;

And then a wise bell-wether sheep
Pursued the trail o'er vale and steep,

And drew the flock behind him, too,
As good bell-wethers always do.

And from that day, o'er hill and glade.
Through those old woods a path was made.


** III.

And many men wound in and out,
And dodged, and turned, and bent about,

And uttered words of righteous wrath,
Because 'twas such a crooked path;

But still they followed—do not laugh—
The first migrations of that calf,

And through this winding wood-way stalked
Because he wobbled when he walked.


** IV.

This forest path became a lane,
that bent and turned and turned again;

This crooked lane became a road,
Where many a poor horse with his load

Toiled on beneath the burning sun,
And traveled some three miles in one.

And thus a century and a half
They trod the footsteps of that calf.


** V.

The years passed on in swiftness fleet,
The road became a village street;

And this, before men were aware,
A city's crowded thoroughfare.

And soon the central street was this
Of a renowned metropolis;

And men two centuries and a half,
Trod in the footsteps of that calf.


** VI.

Each day a hundred thousand rout
Followed the zigzag calf about

And o'er his crooked journey went
The traffic of a continent.

A Hundred thousand men were led,
By one calf near three centuries dead.

They followed still his crooked way,
And lost one hundred years a day;

For thus such reverence is lent,
To well established precedent.


** VII.

A moral lesson this might teach
Were I ordained and called to preach;

For men are prone to go it blind
Along the calf-paths of the mind,

And work away from sun to sun,
To do what other men have done.

They follow in the beaten track,
And out and in, and forth and back,

And still their devious course pursue,
To keep the path that others do.

They keep the path a sacred groove,
Along which all their lives they move.

But how the wise old wood gods laugh,
Who saw the first primeval calf.

Ah, many things this tale might teach—
But I am not ordained to preach.
