#+title: 8 Months Adrift
#+rss_title: 8 Months Adrift
#+pubdate: <2020-08-04>

November 2019 I quit my contracted software job, drove across the country to family, and threw all my shit in a storage locker. In the following months I:

- Met some extended family in Sinaloa, Mexico
- Attended a 3 month batch at the Recurse Center in NYC
  - Gave lighting talks about {emacs,systemd,keyboards}
  - Became a member of a wonderful community
  - Chased many divergent interests
- Conquered an ever-growing backlog of "cool emacs links"
- Started an exercise and diet regimen (and lost some weight!)
- Moved in with my SO
- Improved my typing speed by working through some exercises
- Improved my Clojure programming (and some local scripts with the wonderful Babashka)
- Enjoyed many fantasy {audio,}books

This is the longest period of time I've been unemployed since starting college in the fall of 2012. My SO jokes that I'm ready for retirement as I find ways to fill up my free time between programming and little things like going on walks through nearby trails. I'm very grateful to have been able to take this time (thanks KS cost of living), and feel like I've gotten a peek into what life can be when you have this much time and space (regardless of global pandemic status).

I suppose I'm writing now to remind myself that this time was not wasted. It's easy to find myself drifting along sometimes, seeking escape in everything that's going on in the world, or indulging in occasional "doom scrolling" on social media. It's important to be self aware, realize that everything is habit, and track your long term trends.

Back in May I listed [[file:blog-meta.org][some goals]] for this website, and I think I'm about there with regards to link-ability, and creating a writing and publishing environment tied enough to Emacs that I can just *do the thing*. Perhaps one more nice-to-have would be to publish a subset of notes headings along with the website posts, as some content that makes is here lives in my notes as a reference for awhile before I realize it is worth sharing.

-----

(rambly) In some sense It feels like I've been asleep since the pandemic started. That's not the case, but with so little physical change in surroundings it's easy to trap yourself into feeling that way. When you think like that, it's easy to feel guilty. There's a lingering feeling that today should be the day you "wake up", even though you have been here all this time. What does waking up look like? For myself, it's a moving target. I might say "today, I will get 20 things done" and then feel bad about accomplishing 2, when number 2 on the list turned out to have all the hidden holes and choices that programming projects tend to carry with them. On the other hand, if I finish everything I set out to do, that feels great!, but then I look at the 200 things left in my forever backlog and it becomes harder to respect this small step. Maybe having the space to meditate on the tension between time and ability is a luxurious nonsense problem to have (and yet we still try).

Here's to waking up in spite of that.
