#+title: May Days
#+rss_title: May Days

{{{image(may.png)}}}

There's a nice post/site/idea circulating around, [[https://100daystooffload.com/][100daystooffload]], which encourages people with personal blogs to post once a day for 100 days with low pressure requirements. This notion really vibed with me, I think because I've spent a fair amount of time tweaking this site, and not nearly as much time actually putting stuff out there. So... consider this the first post of that. I plan to [[https://mastodon.social/web/accounts/405380][toot]] these posts to join in on the feed of other bloggers doing the same thing.

** [[#h-a074491a-fbb9-48fe-80af-ec7786fa9a03][Site Meta]]
:PROPERTIES:
:CUSTOM_ID: h-a074491a-fbb9-48fe-80af-ec7786fa9a03
:END:

I think here I'll just layout some of my goals for this site even existing:

- reference material for myself (and potentially have my stuff corrected by others)
- reference material for others (it should be easy to share to an anchor link)
- "wiki like" content, where it's not a big deal if things are edited (this is why every post has a link to it's git history and there are different sort orders on the front page of the site)
- selectively publish posts to an RSS feed
- high integration with my environment (emacs) such that my editing experience in posts leaks to other areas of my workflow
- writing can help clarify thoughts, and take things from "fuzzy" to concrete
- feel ð™°ð™´ðš‚ðšƒð™·ð™´ðšƒð™¸ð™²/match some rice looks
- feel OK "offloading" here/nonsense posts as well
- copy/share stuff I want to preserve (like nice poems or something)

** [[#h-85a7eb4b-3bbc-4dcb-93e5-e96744faac46][High level May goals]]
:PROPERTIES:
:CUSTOM_ID: h-85a7eb4b-3bbc-4dcb-93e5-e96744faac46
:END:

- conquer the 'hardcore' section here at >80wpm https://10fastfingers.com/top1000 (maybe the goal should be 90wpm? the star jump is from 80 to 100)
- write more (wowie)
- keep working out (been doing so every other day)
- "get good" at (ongoing/vague currently -- I've got some specific projects noted down in my [[https://orgmode.org/][org notes]])
  - Clojure
  - Nix
  - org scheduling + agenda modes (related: [[https://notes.neeasade.net/mobile-capture-with-orgzly-termux-and-syncthing.html][my mobile org setup]])
- start searching for a job? part of this ties into the feeling of "getting good" at the above
