#+title: The Calf Path
#+pubdate: <2020-12-17>

A poem by [[https://en.wikipedia.org/wiki/Sam_Walter_Foss][Sam Foss]].

** I.

One day through the primeval wood{{{newline}}}
A calf walked home as good calves should;

But made a trail all bent askew,{{{newline}}}
A crooked trail as all calves do.

Since then three hundred years have fled,{{{newline}}}
And I infer the calf is dead.

** II.

But still he left behind his trail,{{{newline}}}
And thereby hangs my moral tale.

The trail was taken up next day,{{{newline}}}
By a lone dog that passed that way;

And then a wise bell-wether sheep{{{newline}}}
Pursued the trail o'er vale and steep,

And drew the flock behind him, too,{{{newline}}}
As good bell-wethers always do.

And from that day, o'er hill and glade.{{{newline}}}
Through those old woods a path was made.


** III.

And many men wound in and out,{{{newline}}}
And dodged, and turned, and bent about,

And uttered words of righteous wrath,{{{newline}}}
Because 'twas such a crooked path;

But still they followed—do not laugh—{{{newline}}}
The first migrations of that calf,

And through this winding wood-way stalked{{{newline}}}
Because he wobbled when he walked.


** IV.

This forest path became a lane,{{{newline}}}
that bent and turned and turned again;

This crooked lane became a road,{{{newline}}}
Where many a poor horse with his load

Toiled on beneath the burning sun,{{{newline}}}
And traveled some three miles in one.

And thus a century and a half{{{newline}}}
They trod the footsteps of that calf.


** V.

The years passed on in swiftness fleet,{{{newline}}}
The road became a village street;

And this, before men were aware,{{{newline}}}
A city's crowded thoroughfare.

And soon the central street was this{{{newline}}}
Of a renowned metropolis;

And men two centuries and a half,{{{newline}}}
Trod in the footsteps of that calf.


** VI.

Each day a hundred thousand rout{{{newline}}}
Followed the zigzag calf about

And o'er his crooked journey went{{{newline}}}
The traffic of a continent.

A Hundred thousand men were led,{{{newline}}}
By one calf near three centuries dead.

They followed still his crooked way,{{{newline}}}
And lost one hundred years a day;

For thus such reverence is lent,{{{newline}}}
To well established precedent.


** VII.

A moral lesson this might teach{{{newline}}}
Were I ordained and called to preach;

For men are prone to go it blind{{{newline}}}
Along the calf-paths of the mind,

And work away from sun to sun,{{{newline}}}
To do what other men have done.

They follow in the beaten track,{{{newline}}}
And out and in, and forth and back,

And still their devious course pursue,{{{newline}}}
To keep the path that others do.

They keep the path a sacred groove,{{{newline}}}
Along which all their lives they move.

But how the wise old wood gods laugh,{{{newline}}}
Who saw the first primeval calf.

Ah, many things this tale might teach—{{{newline}}}
But I am not ordained to preach.
