#+title: Enchiridion #51
#+post_type: post
#+filetags:
#+pubdate: <2025-07-18>

#+begin_quote
How long will you wait before you consider yourself capable of the best,
and of living in accord with reason? You've been through the reasoning
and accepted the principles. What great master are you waiting for, so
that you can stall your improvement until his arrival? You're no longer
a child, but an adult. If you're negligent and lazy, keep delaying and
making a collection of one good intention after another, naming day
after day on which you'll start to take care of yourself, you'll just go
on without getting better, and you'll live and die miserable.

Right now, consider yourself worthy of living like a grownup, and
someone who's getting better. Let what seems right to you be an iron
law. And if anything comes your way that seems like work, or seems
tempting or glorious or disgraceful, remember that the struggle is on
already, that the Olympics have begun and can't be delayed, that what
you do today -- this minute -- will determine whether progress is made
or lost. Socrates became perfect this way, making everything an
opportunity for his improvement, following only reason. Though you're
not yet a Socrates, you should live as though you intend to become a
Socrates.
#+end_quote

- http://www.ideonautics.net/manual2.htm, section 51

This entry appears towards the end of the manual.
