
#+title: reptile waterfall
#+title_extra:
#+post_type: post
#+filetags: personal
#+rss_title:
#+draft: t
#+pubdate: <2021-01-30>

When jurassic world came out, I was determined to watch a movie by myself. I could already eat out by myself, so I reckoned this would be nothing for an experienced solo adventurer such as myself. Somehow part of this meant that I wanted to get a *BIG SODA* and a *HUGE POPCORN* and basically turn myself into the caricature American stereotype that the rest of the world envisions when they think of the burgerland denizens.

For the first half hour, it was great. I ate so much popcorn and smacked off some Dr pepper or whatever I was into at the time. Heck, I refilled my popcorn before I got to the bottom because the bag was getting cold.

# Then, tragedy  struck. During the supermonkey ball scene I was experiencing a rising tide/need2pee. But during the tense part of the movie I couldn't look away.

# blah blah blah talk about huge relief and then how the scene of them falling off the waterfal was a pee aid for like literally a year
